### ISSUE TITLE
Problems with username in saludoUsuario function

### ISSUE THREAD

**Issue by seminarioA** [seminarioA/tf_taller_web#1]
![image](https://github.com/user-attachments/assets/a6aba807-211a-4f7a-944c-4b73dca7ce1d)
![image](https://github.com/user-attachments/assets/f2b021d2-8bba-4bd9-9445-da886ad20e1a)

**Comment by ipasco01** [comment]
Eso se genera automáticamente lo voy a a cambiar por el id de airtable

**Comment by ipasco01** [comment]
Haciendo los cambios
